apiVersion: v2
appVersion: "1.0"
description: A Helm chart for redash
name: redash-helm
version: 0.1.2
keywords:
  - redash
  - redash-helm
  - helm
  - chart
  - helm-chart
  - kubernetes
maintainers:
- name: pparthesh

dependencies:
  - name: redis
    version: 3.8.1
    repository: https://kubernetes-charts.storage.googleapis.com/
    condition: redis.enabled
  - name: postgresql
    version: 2.6.5
    repository: https://kubernetes-charts.storage.googleapis.com/
    condition: postgresql.enabled
